spring.application.name=Tp_3_Spring_MVC
spring.datasource.url=jdbc:h2:mem:tp3db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=parfait
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.thymeleaf.cache=false